### ISSUE TITLE
Looking forward to your next progress!

### ISSUE THREAD

**Issue by tttousa** [drbh/wasm-fingerprint#1]
I am interested in wasm！Looking forward to your next progress!

**Comment by tttousa** [comment]
Hello！
Thanks for your reply ! I've run the web-example successfully!
I love your project！ And I have some other questions~ I'll appreciate it if you can give me a reply~
（1）I notice that your source codes are based Rust and I've learned that wasm can also support C /C++,so why choose Rust ? I wonder whether your project can be implemented in C/C++ source code.
（2）As a student, I wonder whether wasm_fingerprint_mod.js and wasm_fingerprint_bg.wasm are written by yourself or generated by Emscripten.
（3）I have a little suggestions. As far as I know，there are other fingerprint methods other than canvas，such as webGL，webAudio，clock skew and so on. So,maybe you can have a try to enrich your wasm-fingerprint with these methods !
Finally, Thank you! You are so nice and I love your project !!!

**Comment by drbh** [comment]
duplicated #3
