### ISSUE TITLE
Can you provide me with a web demo（including index.html and javascript files）？Thank you very much！

### ISSUE THREAD

**Issue by tttousa** [drbh/wasm-fingerprint#2]

**Comment by drbh** [comment]
Hey @tttousa 

Thanks for the interest in the project!
 
I've added a standalone web example that includes the `html` `js` and `wasm` files needed.

```bash
cd web-example
```

run a simple server; I use https://www.npmjs.com/package/http-server but there are many options

```bash
http-server
```

Now in the browser at `http://localhost:8080/` you'll see a blank page but `wasm-fingerprint` is loaded into the DOM.

Open up dev-tools and try these commands

```js
const fp = new WasmFingerprint()
fp.make_fingerprint()
// {ms: 9.210000003804453, print: "CT2GFCAR"} 
```
🙌 I hope this is helpful!

Let me know what you think about the project! and let me know if I can help you integrate it with your own use case 😊

**Comment by drbh** [comment]
I've also added a live demo that can be found here https://drbh.github.io/wasm-fingerprint/

**Comment by tttousa** [comment]
Hello！
Thanks for your reply !   I've run the web-example successfully!
I love your project！ And I have some other questions~ I'll appreciate it if you can give me a reply~
（1）I notice that your source codes are based Rust and I've learned that wasm can also support C /C++,so why choose Rust ? I wonder  whether your project can be implemented in C/C++ source code.
（2）As a student, I wonder whether wasm_fingerprint_mod.js and wasm_fingerprint_bg.wasm  are written by yourself or generated by Emscripten.
（3）I have a little suggestions. As far as I know，there are other  fingerprint methods other than canvas，such as webGL，webAudio，clock skew and so on. So,maybe you can have a try to enrich your wasm-fingerprint with these methods !
Finally, Thank you! You are so nice and I love your project !!!
