### ISSUE TITLE
A question about the wasm file in the web-example~

### ISSUE THREAD

**Issue by tttousa** [drbh/wasm-fingerprint#5]
Hi, @drbh
I am so  sorry to bother you again. When I introduced your project to others, I found a new question , which is that the wasm_fingerprint_bg.wasm file in the web-example is not the same as the wasm file auto-generated by the wasm-pack. 
In fact, I have build a project with your rust source code successfully. ( I followed the tutorial on this website step by step： https://rustwasm.github.io/book/game-of-life/hello-world.html ）
But when I try to replace the wasm_fingerprint_bg.wasm file in your web-example with the wasm file auto-generated by wasm-pack, I got this error:
![捕获](https://user-images.githubusercontent.com/38468605/74744118-a122a700-529c-11ea-955a-3e08060fdb89.PNG)
Considering you have mentioned that the wasm_fingerprint_bg.wasm file in  web-example is auto-generated by wasm-pack, so I am confused why I can't make it. ( my wasm-pack version is 0.9.0 ) 
I want to make a web-example just like yours. 
Can you give me some help or advice ?   Please~~~~~
Looking forward to your feedback！Thank you！

**Comment by tttousa** [comment]
Can you give me some help or advice ? Please~~~~~
Looking forward to your feedback！Thank you！

**Comment by drbh** [comment]
Hey @tttousa 

You may have missed a point in a earlier comment about making modifications to the computer generated file. I’ve copied the relevant information below.

> Both of those files are auto generated (with the exception to come changes in wasm_fingerprint_mod.js) note the _bg which stands for bindgen, which creates these files. The reason **I added _mod to the first file is because I modified lines ~405:415 to allow wasm-fingerprint to bind to the window when its done loading.** This is done for the end user's convenience and to make the lib easy to use. 
[original comment](https://github.com/drbh/wasm-fingerprint/issues/3#issuecomment-582577792)

The error message in your phot suggests that your script is failing to load the wasm file. Please compare the file you generated with the file included in the web-example and you should see that only a couple of the lines are different (those are the changes I made). 

ps: make sure you are also using wasm-pack to build the correct target: `no-modules` [more info here](https://rustwasm.github.io/wasm-pack/book/commands/build.html#target)

Hope this helps!

**Comment by tttousa** [comment]
Thank you！@drbh
I think I find the reason of my question—— I haven't used wasm-pack to build the correct target: no-modules, which cause I have the different wasm files.
And I find another point that you have some annotated codes in wasm_fingerprint_mod.js :
![捕获](https://user-images.githubusercontent.com/38468605/75104712-51026680-5647-11ea-81ad-9dc47e008671.PNG)
I make these annotated codes available in my JS file.  And with the wasm generaed by wasm-pack with the correct target: no-modules, my web-example run successfully !
Thank you for the reply ! You are the best author in github I have seen !
